### ISSUE TITLE
Нет уверенности, что можно реализовать `StatefulMap`

### ISSUE THREAD

**Issue by faucct** [flame-stream/halco#1]
Не хватает примеров реализации графов с операцией StatefulMap. По-моему она нереализуема в графе.
Как минимум нужно показать, что проекцию можно переставлять местами с StatefulMap, а фильтр – нет. Причём фильтр по тому же ключу, что использует StatefulMap, – можно.

**Comment by penguin-boxx** [comment]
Этот вопрос после групп свойств закрыт или ещё нет?
